import type { EmitterConfig } from '../../types';

/**
 * Pre-designed emitter configurations for Faithful.
 * All values use seconds for time and radians for angles.
 */

// ============================================================
// Spell Effects
// ============================================================

export const meteorTrailConfig: EmitterConfig = {
  name: 'meteorTrail',
  spawnRate: 800,
  maxParticles: 2000,
  shape: 'cone',
  spawnRadius: 4,
  angle: Math.PI / 2,
  angleSpread: Math.PI / 6,
  speedMin: 40,
  speedMax: 120,
  lifeMin: 0.2,
  lifeMax: 0.6,
  sizeMin: 2,
  sizeMax: 6,
  sizeOverLife: 0.2,
  colorStart: [1, 0.6, 0.1, 1],
  colorEnd: [0.2, 0.05, 0, 0],
  gravity: [0, 30],
  drag: 0.5,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -2,
  rotationSpeedMax: 2,
};

export const healSparklesConfig: EmitterConfig = {
  name: 'healSparkles',
  spawnRate: 200,
  maxParticles: 600,
  shape: 'circle',
  spawnRadius: 12,
  angle: -Math.PI / 2,
  angleSpread: Math.PI / 3,
  speedMin: 10,
  speedMax: 40,
  lifeMin: 0.5,
  lifeMax: 1.2,
  sizeMin: 1,
  sizeMax: 3,
  sizeOverLife: 0,
  colorStart: [0.4, 1, 0.6, 1],
  colorEnd: [0.8, 1, 0.9, 0],
  gravity: [0, -10],
  drag: 0.2,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -1,
  rotationSpeedMax: 1,
};

export const lightningArcConfig: EmitterConfig = {
  name: 'lightningArc',
  spawnRate: 600,
  maxParticles: 900,
  burstCount: 60,
  duration: 0.4,
  shape: 'point',
  spawnRadius: 0,
  angle: 0,
  angleSpread: Math.PI * 2,
  speedMin: 150,
  speedMax: 400,
  lifeMin: 0.05,
  lifeMax: 0.15,
  sizeMin: 1,
  sizeMax: 3,
  sizeOverLife: 0.5,
  colorStart: [0.8, 0.9, 1, 1],
  colorEnd: [0.2, 0.4, 1, 0],
  gravity: [0, 0],
  drag: 2.0,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -5,
  rotationSpeedMax: 5,
};

export const shieldBubbleConfig: EmitterConfig = {
  name: 'shieldBubble',
  spawnRate: 120,
  maxParticles: 300,
  shape: 'circle',
  spawnRadius: 20,
  angle: 0,
  angleSpread: Math.PI * 2,
  speedMin: 2,
  speedMax: 8,
  lifeMin: 1.0,
  lifeMax: 2.0,
  sizeMin: 2,
  sizeMax: 5,
  sizeOverLife: 0,
  colorStart: [0.3, 0.7, 1, 0.8],
  colorEnd: [0.1, 0.3, 0.8, 0],
  gravity: [0, 0],
  drag: 0.1,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -1,
  rotationSpeedMax: 1,
};

// ============================================================
// Weather Particles
// ============================================================

export const rainConfig: EmitterConfig = {
  name: 'rain',
  spawnRate: 2000,
  maxParticles: 8000,
  shape: 'rect',
  spawnRadius: 400,
  angle: -Math.PI / 2 + 0.1,
  angleSpread: 0.05,
  speedMin: 200,
  speedMax: 350,
  lifeMin: 0.4,
  lifeMax: 0.8,
  sizeMin: 1,
  sizeMax: 2,
  sizeOverLife: 1,
  colorStart: [0.6, 0.7, 0.9, 0.6],
  colorEnd: [0.6, 0.7, 0.9, 0.2],
  gravity: [0, 50],
  drag: 0.0,
  blendMode: 'normal',
  rotationMin: 0,
  rotationMax: 0,
  rotationSpeedMin: 0,
  rotationSpeedMax: 0,
};

export const snowConfig: EmitterConfig = {
  name: 'snow',
  spawnRate: 400,
  maxParticles: 3000,
  shape: 'rect',
  spawnRadius: 400,
  angle: -Math.PI / 2,
  angleSpread: Math.PI / 4,
  speedMin: 10,
  speedMax: 30,
  lifeMin: 2.0,
  lifeMax: 4.0,
  sizeMin: 2,
  sizeMax: 4,
  sizeOverLife: 0.5,
  colorStart: [1, 1, 1, 0.9],
  colorEnd: [1, 1, 1, 0.3],
  gravity: [0, 5],
  drag: 0.3,
  blendMode: 'normal',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -0.5,
  rotationSpeedMax: 0.5,
};

export const dustConfig: EmitterConfig = {
  name: 'dust',
  spawnRate: 80,
  maxParticles: 600,
  shape: 'rect',
  spawnRadius: 300,
  angle: 0,
  angleSpread: Math.PI / 6,
  speedMin: 5,
  speedMax: 20,
  lifeMin: 1.5,
  lifeMax: 3.0,
  sizeMin: 1,
  sizeMax: 3,
  sizeOverLife: 0.3,
  colorStart: [0.7, 0.6, 0.4, 0.5],
  colorEnd: [0.5, 0.4, 0.2, 0],
  gravity: [0, -2],
  drag: 0.4,
  blendMode: 'normal',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -0.3,
  rotationSpeedMax: 0.3,
};

export const embersConfig: EmitterConfig = {
  name: 'embers',
  spawnRate: 150,
  maxParticles: 1200,
  shape: 'rect',
  spawnRadius: 200,
  angle: -Math.PI / 2,
  angleSpread: Math.PI / 5,
  speedMin: 10,
  speedMax: 40,
  lifeMin: 1.0,
  lifeMax: 2.5,
  sizeMin: 1,
  sizeMax: 3,
  sizeOverLife: 0.1,
  colorStart: [1, 0.5, 0.1, 0.9],
  colorEnd: [0.3, 0.05, 0, 0],
  gravity: [0, -15],
  drag: 0.2,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -1,
  rotationSpeedMax: 1,
};

// ============================================================
// Ambient Particles
// ============================================================

export const firefliesConfig: EmitterConfig = {
  name: 'fireflies',
  spawnRate: 30,
  maxParticles: 200,
  shape: 'circle',
  spawnRadius: 150,
  angle: 0,
  angleSpread: Math.PI * 2,
  speedMin: 5,
  speedMax: 15,
  lifeMin: 2.0,
  lifeMax: 4.0,
  sizeMin: 1.5,
  sizeMax: 3,
  sizeOverLife: 0.5,
  colorStart: [0.8, 1, 0.2, 0.9],
  colorEnd: [0.4, 0.6, 0.1, 0],
  gravity: [0, 0],
  drag: 0.1,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: 0,
  rotationSpeedMin: 0,
  rotationSpeedMax: 0,
};

export const pollenConfig: EmitterConfig = {
  name: 'pollen',
  spawnRate: 50,
  maxParticles: 400,
  shape: 'rect',
  spawnRadius: 250,
  angle: -Math.PI / 2,
  angleSpread: Math.PI / 3,
  speedMin: 2,
  speedMax: 10,
  lifeMin: 2.0,
  lifeMax: 4.0,
  sizeMin: 1,
  sizeMax: 2.5,
  sizeOverLife: 0.2,
  colorStart: [1, 0.95, 0.7, 0.7],
  colorEnd: [1, 0.9, 0.5, 0],
  gravity: [0, -3],
  drag: 0.3,
  blendMode: 'normal',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -0.5,
  rotationSpeedMax: 0.5,
};

export const magicDustConfig: EmitterConfig = {
  name: 'magicDust',
  spawnRate: 100,
  maxParticles: 800,
  shape: 'circle',
  spawnRadius: 60,
  angle: 0,
  angleSpread: Math.PI * 2,
  speedMin: 5,
  speedMax: 25,
  lifeMin: 1.0,
  lifeMax: 2.0,
  sizeMin: 1,
  sizeMax: 3,
  sizeOverLife: 0,
  colorStart: [0.6, 0.2, 1, 0.8],
  colorEnd: [0.2, 0, 0.5, 0],
  gravity: [0, -5],
  drag: 0.2,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -2,
  rotationSpeedMax: 2,
};

// ============================================================
// Combat Particles
// ============================================================

export const bloodSprayConfig: EmitterConfig = {
  name: 'bloodSpray',
  spawnRate: 600,
  maxParticles: 800,
  burstCount: 40,
  duration: 0.3,
  shape: 'circle',
  spawnRadius: 4,
  angle: 0,
  angleSpread: Math.PI / 2,
  speedMin: 50,
  speedMax: 150,
  lifeMin: 0.2,
  lifeMax: 0.5,
  sizeMin: 1.5,
  sizeMax: 4,
  sizeOverLife: 0.2,
  colorStart: [0.7, 0.05, 0.05, 1],
  colorEnd: [0.3, 0, 0, 0],
  gravity: [0, 60],
  drag: 0.8,
  blendMode: 'normal',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -3,
  rotationSpeedMax: 3,
};

export const blockSparksConfig: EmitterConfig = {
  name: 'blockSparks',
  spawnRate: 800,
  maxParticles: 600,
  burstCount: 30,
  duration: 0.15,
  shape: 'point',
  spawnRadius: 0,
  angle: 0,
  angleSpread: Math.PI,
  speedMin: 80,
  speedMax: 200,
  lifeMin: 0.05,
  lifeMax: 0.15,
  sizeMin: 1,
  sizeMax: 3,
  sizeOverLife: 0.5,
  colorStart: [1, 1, 0.8, 1],
  colorEnd: [0.5, 0.5, 0.4, 0],
  gravity: [0, 20],
  drag: 1.5,
  blendMode: 'additive',
  rotationMin: 0,
  rotationMax: 0,
  rotationSpeedMin: 0,
  rotationSpeedMax: 0,
};

export const deathDissolveConfig: EmitterConfig = {
  name: 'deathDissolve',
  spawnRate: 300,
  maxParticles: 500,
  burstCount: 80,
  duration: 1.0,
  shape: 'circle',
  spawnRadius: 12,
  angle: 0,
  angleSpread: Math.PI * 2,
  speedMin: 5,
  speedMax: 30,
  lifeMin: 0.5,
  lifeMax: 1.2,
  sizeMin: 2,
  sizeMax: 5,
  sizeOverLife: 0.1,
  colorStart: [0.2, 0.2, 0.2, 0.9],
  colorEnd: [0.05, 0.05, 0.05, 0],
  gravity: [0, -5],
  drag: 0.3,
  blendMode: 'normal',
  rotationMin: 0,
  rotationMax: Math.PI * 2,
  rotationSpeedMin: -1,
  rotationSpeedMax: 1,
};

/**
 * Registry of all named emitter presets.
 */
export const EMITTER_REGISTRY: Record<string, EmitterConfig> = {
  meteorTrail: meteorTrailConfig,
  healSparkles: healSparklesConfig,
  lightningArc: lightningArcConfig,
  shieldBubble: shieldBubbleConfig,
  rain: rainConfig,
  snow: snowConfig,
  dust: dustConfig,
  embers: embersConfig,
  fireflies: firefliesConfig,
  pollen: pollenConfig,
  magicDust: magicDustConfig,
  bloodSpray: bloodSprayConfig,
  blockSparks: blockSparksConfig,
  deathDissolve: deathDissolveConfig,
};
